/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.BookDAO;
import static DAO.BookDAO.getListSach;
import DAO.ConnectDAO;
import DTO.Book;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tuan Dung
 */
public class AddBook extends javax.swing.JInternalFrame {
    //private static String ma;
    public AddBook(){
        initComponents();        
        
        LoadListBook();
    }
    
    public void LoadListBook(){
        String sql = "SELECT MASOSACH as [Mã sách], LOAISACH as [Loại sách], TENSACH as [Tên sách] , TACGIA as [Tác giả] , NXB as [Nhà xuất bản] , TRANGTHAI as [Trạng thái] FROM SACH ORDER BY MASOSACH asc";
        BookDAO.LoadData(sql, tbBook);
        autoId();
        ProcessCtr(false);
        this.btnAddBook.setEnabled(true);
    }
     
    public static PreparedStatement pst = null;
    public static ResultSet rs = null;
    public static Connection conn = ConnectDAO.getSQLServerConnection();
    
    private void autoId()
    {
        try {
             String sql="SELECT MASOSACH FROM SACH ORDER BY MASOSACH DESC";
         
            pst=(PreparedStatement) conn.prepareStatement(sql);
            rs=pst.executeQuery();
           if(rs.next())
           {
                String rnno=rs.getString("MASOSACH");
                int co=rnno.length();
               String txt= rnno.substring(0, 2);
               String num=rnno.substring(2, co);
               int n=Integer.parseInt(num);
               n++;
               String snum=Integer.toString(n);
               String ftxt=txt+snum;
               txtBookID.setText(ftxt);
            
           }
           else
           {
               txtBookID.setText("BI1000");
           }
           
                            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
       
    }
    /*
       public void LoadListBook()
    {
        String[] arr = {"Mã sách", "Loại sách", "Tên sách", "Tác giả", "NXB", "Trạng thái"};
        DefaultTableModel model = new DefaultTableModel(arr, 0);
        ArrayList<Book> list = new ArrayList<Book>();
        list = BookAll();
        Book b = new Book();
        for(int i = 0; i < list.size(); i++)
        {
            b = list.get(i); 
            String ms = b.getMaSoSach();
            String ls = b.getLoaiSach();
            String ts = b.getTenSach();
            String tg = b.getTacGia();
            String nxb = b.getNXB();
            String tt = b.getTrangThai();
            Object[] row = {ms, ls, ts, tg, nxb, tt};
            model.addRow(row);
        }
        tbBook.setModel(model);
    }
      public static ArrayList<Book> BookAll()
    {
        return getListSach();
    }
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBook = new javax.swing.JTable();
        txtSearchBook = new javax.swing.JTextField();
        btnSearchBook = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAddBook = new javax.swing.JButton();
        btnDeleteBook = new javax.swing.JButton();
        btnUpdateBook = new javax.swing.JButton();
        btnClearBook = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBookID = new javax.swing.JTextField();
        txtBookName = new javax.swing.JTextField();
        txtTacGia = new javax.swing.JTextField();
        txtNXB = new javax.swing.JTextField();
        cbLoaiSach = new javax.swing.JComboBox<>();
        cmbTrangThai = new javax.swing.JComboBox<>();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1012, 533));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 48)); // NOI18N
        jLabel1.setText("Sách");

        tbBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBookMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbBook);

        btnSearchBook.setText("Tìm kiếm");
        btnSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBookActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAddBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new.png"))); // NOI18N
        btnAddBook.setText("Thêm");
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });

        btnDeleteBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete.png"))); // NOI18N
        btnDeleteBook.setText("Xóa");
        btnDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBookActionPerformed(evt);
            }
        });

        btnUpdateBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Reset.png"))); // NOI18N
        btnUpdateBook.setText("Sửa");
        btnUpdateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBookActionPerformed(evt);
            }
        });

        btnClearBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Clear-icon.png"))); // NOI18N
        btnClearBook.setText("Clear");
        btnClearBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteBook, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateBook, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClearBook, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteBook, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateBook, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClearBook, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Mã sách");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Loại sách");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Tác giả");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Tên sách");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("NXB");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Trạng thái");

        txtBookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookNameActionPerformed(evt);
            }
        });

        cbLoaiSach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn loại sách", "Giáo khoa", "Truyện tranh", "Trinh thám", "Khoa học", "Truyện ngắn", "Truyện dài", "Tiểu thuyết", " " }));

        cmbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trạng thái", "Còn", "Hết", " " }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBookID, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(cbLoaiSach, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNXB, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(cmbTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel7)
                        .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbLoaiSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSearchBook)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        LoadListBook();
    }//GEN-LAST:event_formComponentShown
   
    private void clearFild(){
      txtBookID.setText("");
      txtBookName.setText("");      
      cmbTrangThai.setSelectedItem(0);
      cbLoaiSach.setSelectedIndex(0);
      txtNXB.setText("");   
      txtTacGia.setText("");
      txtSearchBook.setText("");
    }
      
    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        
        if (txtBookID.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mã sách không được rỗng");
            txtBookID.requestFocus();
            return;
        }
        else if (cbLoaiSach.getSelectedItem().equals("")){
             JOptionPane.showMessageDialog(null, "Loại sách không được rỗng");
             cbLoaiSach.requestFocus();
             return;
        }
        else if (txtBookName.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Tên không được rỗng");
             txtBookName.requestFocus();
             return;
             }
        else if (txtTacGia.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Tác giả không được rỗng");
             txtTacGia.requestFocus();
             return;
             }
        else if (txtNXB.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Nhà xuất bản không được rỗng");
             txtNXB.requestFocus();
             return;
        }
        else if (cmbTrangThai.getSelectedItem().equals("")){
             JOptionPane.showMessageDialog(null, "Trạng thái không được rỗng");
             cmbTrangThai.requestFocus();
             return;
        }
        if (CheckTrungMASACH()== true){
            JOptionPane.showMessageDialog(null, "Mã sách đã tồn tại!");
            txtBookID.requestFocus();
            return;
        }
        else{
            BookDAO.InsertBook(this.txtBookID.getText().trim(), this.cbLoaiSach.getSelectedItem().toString(), this.txtBookName.getText().trim(), this.txtTacGia.getText().trim(), this.txtNXB.getText().trim(), this.cmbTrangThai.getSelectedItem().toString());
            clearFild();
            LoadListBook();                     
        }
    }//GEN-LAST:event_btnAddBookActionPerformed

    private void btnDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBookActionPerformed
       if (this.txtBookID.getText().length() == 0)
           JOptionPane.showMessageDialog(null, "Bạn cần chọn sách để xóa!");
       else
       {
           if (JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn xóa sách " +this.txtBookID.getText()+ " hay không", "Thông báo", 2) == 0 )
               BookDAO.DeleteBook(this.txtBookID.getText());
           LoadListBook();
           clearFild();
       }

    }//GEN-LAST:event_btnDeleteBookActionPerformed

    private void tbBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBookMouseClicked
        ProcessCtr(true);
        this.btnAddBook.setEnabled(false);
        DefaultTableModel tmodel = (DefaultTableModel)tbBook.getModel();
        int selectrowindex = tbBook.getSelectedRow();
        
        txtBookID.setText(tmodel.getValueAt(selectrowindex, 0).toString());
        cbLoaiSach.setSelectedItem(tmodel.getValueAt(selectrowindex, 1).toString());
        txtBookName.setText(tmodel.getValueAt(selectrowindex, 2).toString());
        txtTacGia.setText(tmodel.getValueAt(selectrowindex, 3).toString());
        txtNXB.setText(tmodel.getValueAt(selectrowindex, 4).toString());
        cmbTrangThai.setSelectedItem(tmodel.getValueAt(selectrowindex, 5).toString());
    }//GEN-LAST:event_tbBookMouseClicked

    private void btnClearBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearBookActionPerformed
       clearFild();
       LoadListBook();
    }//GEN-LAST:event_btnClearBookActionPerformed

    private void btnUpdateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBookActionPerformed
           if (txtBookID.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mã sách không được rỗng");
            txtBookID.requestFocus();
            return;
        }
        else if (cbLoaiSach.getSelectedItem().equals("")){
             JOptionPane.showMessageDialog(null, "Loại sách không được rỗng");
             cbLoaiSach.requestFocus();
             return;
        }
        else if (txtBookName.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Tên không được rỗng");
             txtBookName.requestFocus();
             return;
             }
        else if (txtTacGia.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Tác giả không được rỗng");
             txtTacGia.requestFocus();
             return;
             }
        else if (txtNXB.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Nhà xuất bản không được rỗng");
             txtNXB.requestFocus();
             return;
        }
        else if (cmbTrangThai.getSelectedItem().equals("")){
             JOptionPane.showMessageDialog(null, "Trạng thái không được rỗng");
             cmbTrangThai.requestFocus();
             return;       
        }
        else{
            BookDAO.UpdateBook(this.txtBookID.getText().trim(), this.cbLoaiSach.getSelectedItem().toString(), this.txtBookName.getText().trim(), this.txtTacGia.getText().trim(), this.txtNXB.getText().trim(), this.cmbTrangThai.getSelectedItem().toString());
            LoadListBook();
            clearFild();           
        }
    }//GEN-LAST:event_btnUpdateBookActionPerformed

    private void btnSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBookActionPerformed
        if (this.txtSearchBook.getText().length() == 0)
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập từ khóa cần tìm", "Thông báo", 1);
        else
        {
            String sql1 = "select * from dbo.SACH where MASOSACH like N'%"+this.txtSearchBook.getText()+"%' or LOAISACH like N'%"+this.txtSearchBook.getText()+"%' or TENSACH like N'%"+this.txtSearchBook.getText()+"%' or TACGIA like N'%"+this.txtSearchBook.getText()+"%' or NXB like N'%"+this.txtSearchBook.getText()+"%' or TRANGTHAI like '%"+this.txtSearchBook.getText()+"%'"; // TENSACH like N'%"+this.txtSearchBook.getText()+"%' or TACGIA like N'%"+this.txtSearchBook.getText()+"%' or  NXB = like N'%"+this.txtSearchBook.getText()+"%' or TRANGTHAI like N'%"+this.txtSearchBook.getText()+"%'";
            BookDAO.LoadData(sql1, tbBook);
        }
    }//GEN-LAST:event_btnSearchBookActionPerformed

    private void txtBookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookNameActionPerformed

    private boolean CheckTrungMASACH(){
        try {
            Connection connection = ConnectDAO.getSQLServerConnection();
            
            String query = "SELECT * FROM DBO.SACH WHERE MASOSACH = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, txtBookID.getText());
            
            ResultSet rs =  ps.executeQuery();
            
            while (rs.next()){
                return true;
            }
            ConnectDAO.closeConnection(connection);
        } catch (SQLException ex) {
            Logger.getLogger(Addmember.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
       
    public void ProcessCtr(boolean b){
        this.btnAddBook.setEnabled(b);
        this.btnDeleteBook.setEnabled(b);
        this.btnUpdateBook.setEnabled(b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnClearBook;
    private javax.swing.JButton btnDeleteBook;
    private javax.swing.JButton btnSearchBook;
    private javax.swing.JButton btnUpdateBook;
    private javax.swing.JComboBox<String> cbLoaiSach;
    private javax.swing.JComboBox<String> cmbTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbBook;
    private javax.swing.JTextField txtBookID;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JTextField txtNXB;
    private javax.swing.JTextField txtSearchBook;
    private javax.swing.JTextField txtTacGia;
    // End of variables declaration//GEN-END:variables
}
